version: "3.8"

services:

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      NODE_ENV: development
      PORT: 3333
      JWT_SECRET: mudar_123
      DATABASE_URL: postgresql://docker:docker@db:5432/lumi_challenge_db?schema=public
    volumes:
      - ./api:/app:cached
      - /app/node_modules
    depends_on:
      - db
    command: sh -c "pnpm prisma migrate deploy && pnpm run seed && pnpm run dev"
    # Define a política de reinicialização para manter o serviço ativo
    # restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:3333
      PORT: 3000
    volumes:
      - ./web:/app:cached
      - /app/node_modules
    depends_on:
      - api
    # Define a política de reinicialização para manter o serviço ativo
    # restart: unless-stopped

  db:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: lumi_challenge_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Define a política de reinicialização para manter o serviço ativo
    # restart: unless-stopped

volumes:
  postgres_data:
    name: postgres_data
